// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
/// ERC-4626 Tokenized Vault flows (deposit / withdraw)
/// <https://eips.ethereum.org/EIPS/eip-4626>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    /// vault contract
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Call metadata (only available on chains with DetailLevel: EXTENDED)
    #[prost(message, optional, tag="5")]
    pub call: ::core::option::Option<Call>,
    /// Native block/log position fields
    #[prost(uint32, tag="6")]
    pub block_index: u32,
    #[prost(oneof="log::Log", tags="10, 11")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// events
        #[prost(message, tag="10")]
        Deposit(super::Deposit),
        #[prost(message, tag="11")]
        Withdraw(super::Withdraw),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Call {
    #[prost(uint32, tag="1")]
    pub index: u32,
    #[prost(uint64, tag="2")]
    pub begin_ordinal: u64,
    #[prost(uint64, tag="3")]
    pub end_ordinal: u64,
    /// sender
    #[prost(bytes="vec", tag="4")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// recipient
    #[prost(bytes="vec", tag="5")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="6")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_consumed: u64,
    #[prost(uint64, tag="8")]
    pub gas_limit: u64,
    #[prost(uint32, tag="9")]
    pub depth: u32,
    #[prost(uint32, tag="10")]
    pub parent_index: u32,
    #[prost(enumeration="CallType", tag="11")]
    pub call_type: i32,
}
/// Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Deposit {
    /// address
    #[prost(bytes="vec", tag="10")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="11")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    /// uint256 (underlying deposited)
    #[prost(string, tag="12")]
    pub assets: ::prost::alloc::string::String,
    /// uint256 (vault shares minted)
    #[prost(string, tag="13")]
    pub shares: ::prost::alloc::string::String,
}
/// Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Withdraw {
    /// address
    #[prost(bytes="vec", tag="10")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="11")]
    pub receiver: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="12")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    /// uint256 (underlying withdrawn)
    #[prost(string, tag="13")]
    pub assets: ::prost::alloc::string::String,
    /// uint256 (vault shares burned)
    #[prost(string, tag="14")]
    pub shares: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallType {
    Unspecified = 0,
    Call = 1,
    Callcode = 2,
    Delegate = 3,
    Static = 4,
    Create = 5,
}
impl CallType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CallType::Unspecified => "CALL_TYPE_UNSPECIFIED",
            CallType::Call => "CALL_TYPE_CALL",
            CallType::Callcode => "CALL_TYPE_CALLCODE",
            CallType::Delegate => "CALL_TYPE_DELEGATE",
            CallType::Static => "CALL_TYPE_STATIC",
            CallType::Create => "CALL_TYPE_CREATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CALL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CALL_TYPE_CALL" => Some(Self::Call),
            "CALL_TYPE_CALLCODE" => Some(Self::Callcode),
            "CALL_TYPE_DELEGATE" => Some(Self::Delegate),
            "CALL_TYPE_STATIC" => Some(Self::Static),
            "CALL_TYPE_CREATE" => Some(Self::Create),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
