// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultEvents {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<VaultEvent>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultEvent {
    #[prost(string, tag="1")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block: u64,
    #[prost(uint64, tag="3")]
    pub timestamp: u64,
    #[prost(string, tag="4")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub assets: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub shares: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub implied_share_price: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="11")]
    pub log_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultMetricsList {
    #[prost(message, repeated, tag="1")]
    pub metrics: ::prost::alloc::vec::Vec<VaultMetrics>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultMetrics {
    #[prost(string, tag="1")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block: u64,
    #[prost(uint64, tag="3")]
    pub timestamp: u64,
    #[prost(string, tag="4")]
    pub share_price: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub share_price_source: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub total_assets: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub total_supply: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub net_deposited_assets: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub net_flow_assets: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub depositor_count: u64,
    #[prost(uint64, tag="11")]
    pub last_event_block: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultMeta {
    #[prost(string, tag="1")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub asset: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub asset_symbol: ::prost::alloc::string::String,
    #[prost(uint32, tag="4")]
    pub asset_decimals: u32,
    #[prost(uint32, tag="5")]
    pub share_decimals: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewDepositors {
    #[prost(string, repeated, tag="1")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
